theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Karachi

title: Orbixio 
tagline: A blog dedicated to Offensive Tradecraft and ART (Advanced Red Teaming)
description: \x21\x79\x61\x64\x79\x72\x65\x76\x65\x20\x73\x67\x6e\x69\x68\x74\x20\x77\x65\x6e\x20\x67\x6e\x69\x6e\x72\x61\x65\x6c\x20\x74\x6e\x65\x64\x75\x74\x73\x20\x79\x74\x69\x72\x75\x63\x65\x73\x20\x72\x65\x62\x79\x63\x20\x67\x6e\x69\x72\x69\x70\x73\x61\x20\x6e\x61\x20\x6d\x27\x49
url: "https://orbixio.netlify.app"

github:
  username: orbixio 
social:
  name: Muhammad Usman
  email: orbixio@proton.me 
  links:
    - https://github.com/orbixio 

theme_mode: dark 
cdn: "https://chirpy-img.netlify.app"
avatar: "https://raw.githubusercontent.com/orbixio/orbixio.github.io/f336a9d89ffd5084c43242124aa9d880627a075b/assets/img/air-crash-burning-falling-plane-plane-crashed-ground_93314-3412.png"
toc: true

assets:
  self_host:
    enabled: 
    env: production

pwa:
  enabled: true 
  cache:
    enabled: true 
    deny_paths:
    
paginate: 10

baseurl: ""
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order
  app:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
